spring:
  datasource:
    url: jdbc:h2:file:./data/medilens_dev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

medilens:
  storage:
    reports-dir: ./data/reports
